[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true


# [templates.program]
# imput_path = "~/.dotfiles/homeManagerModules/apps/matugen/templates/program.conf"
# output_path = "~/.config/kitty/colors.conf"



[templates.kitty]
input_path = '~/.dotfiles/homeManagerModules/apps/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'


#[templates.rofi]
#input_path = '~/.dotfiles/homeManagerModules/apps/matugen/templates/rofi-colors.conf'
#output_path = '~/.config/rofi/colors.rasi'


